version: '2'
services:
  consumer:
    container_name: consumer
    build: hellopact-consumer
    links:
      - producer:producer
    ports:
      - "8080:8080"
  producer:
    container_name: producer
    build: hellopact-producer
    ports:
      - "8082:8082"
