micronaut:
  application:
    name: hellomicronaut
  server:
    port: 9876
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
jpa:
  default:
    packages-to-scan:
    - 'se.david.labs'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true